version: '3.1'

services:
  mysql:
    container_name: mysql
    restart: always
    image: mysql
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always
    ports:
      - 3306:3306
    networks:
      - contohlapak_network
    environment:
      MYSQL_DATABASE: contohlapak
      MYSQL_ROOT_PASSWORD: pass
  redis:
    container_name: redis
    image: redis
    restart: always
    ports:
      - 6379:6379
    networks:
      - contohlapak_network
  phpmyadmin:
    container_name: phpmyadmin
    restart: always
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"
    networks:
      - contohlapak_network
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: pass
  contohlapak:
    container_name: contohlapak
    restart: always
    # image: greyhats13/contohlapak:latest
    build:
      dockerfile: Dockerfile
      context: .
    # ports:
    #   - 9090:9090
    networks:
      - contohlapak_network
    environment:
      - MYSQL_ENABLED=true
      - REDIS_ENABLED=true
      - LOAD_BALANCED=true
      - LISTEN_PORT=9090
      - MYSQL_ADDR=mysql:3306
      - MYSQL_USER=root
      - MYSQL_PASS=pass
      - MYSQL_ROOT_PASSWORD=pass
      - MYSQL_DB=contohlapak
      - REDIS_ADDR=redis:6379
      # - HEADER_AUTH_KEY=X-CONTOHLAPAK-AUTH
    depends_on:
      - mysql
      - redis
      - phpmyadmin
  nginx:
    container_name: nginx
    image: nginx:latest
    # build:
    #   dockerfile: Dockerfile-nginx
    #   context: .
    networks:
      - contohlapak_network
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - ./nginx/conf/:/etc/nginx/conf.d/:ro
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
    depends_on: 
      - contohlapak
  certbot:
    container_name: cerbot
    image: certbot/certbot
    networks:
      - contohlapak_network
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw
networks:
  contohlapak_network:
    driver: bridge
volumes:
  mysql_data:
    driver: local
  